import protobuf from "protobufjs";
const { Message, Field } = protobuf;

Field.d(1, "fixed32", "required")(Message.prototype, "id");
Field.d(2, "float", "required")(Message.prototype, "pox");
Field.d(3, "float", "required")(Message.prototype, "poy");
Field.d(4, "float", "required")(Message.prototype, "roy");
// Field.d(1, "fixed32", "optional")(Message.prototype, "id");
// Field.d(2, "string", "optional")(Message.prototype, "nickname");
// Field.d(3, "string", "optional")(Message.prototype, "email");
// Field.d(4, "string", "optional")(Message.prototype, "password");
// Field.d(5, "fixed32", "optional")(Message.prototype, "age");
// Field.d(6, "fixed32", "optional")(Message.prototype, "birth");
// Field.d(7, "string", "optional")(Message.prototype, "nation");
// Field.d(8, "fixed32", "optional")(Message.prototype, "created_at");
// Field.d(9, "fixed32", "optional")(Message.prototype, "updated_at");
// Field.d(10, "fixed32", "optional")(Message.prototype, "user_id");
// Field.d(11, "fixed32", "optional")(Message.prototype, "server");
// Field.d(12, "string", "optional")(Message.prototype, "authority");
// Field.d(13, "string", "optional")(Message.prototype, "type");
// Field.d(14, "string", "optional")(Message.prototype, "state");
// Field.d(15, "string", "optional")(Message.prototype, "avatar");
// Field.d(16, "string", "optional")(Message.prototype, "space");
// Field.d(17, "fixed32", "optional")(Message.prototype, "pox");
// Field.d(18, "fixed32", "optional")(Message.prototype, "poy");
// Field.d(19, "fixed32", "optional")(Message.prototype, "poz");
// Field.d(20, "fixed32", "optional")(Message.prototype, "roy");
// Field.d(21, "bool", "optional")(Message.prototype, "service");
// Field.d(22, "bool", "optional")(Message.prototype, "marketing");
// Field.d(23, "bool", "optional")(Message.prototype, "personal");
// Field.d(24, "string", "optional")(Message.prototype, "cert_email");
// Field.d(25, "string", "optional")(Message.prototype, "cert_pass");

export default Message;
